version: "3"
services:
  fastapi-task-manager:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000 # ホストマシンのポート8000を、docker内のポート8000に接続する
    environment:
      - MYSQL_USER=hoge
      - MYSQL_PASSWORD=hoge
      - MYSQL_DATABASE=fastapi-task-manager
  mysql:
    image: mysql:8.0
    platform: linux/x86_64 # M1 Macの場合必要
    environment:
      MYSQL_DATABASE: fastapi-task-manager
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: hoge
      MYSQL_PASSWORD: hoge
      TZ: "Asia/Tokyo" # タイムゾーンを日本時間に設定
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password # MySQL8.0ではデフォルトが"caching_sha2_password"で、ドライバが非対応のため変更
    ports:
      - 33306:3306 # ホストマシンのポート33306を、docker内のポート3306に接続する
volumes:
  mysql_data:
